### ISSUE TITLE
Wall corner bottom right is missing

### ISSUE THREAD

**Issue by i9or** [gd754/tetris#6]
This part is missing in the tile sheet:

<img width="96" alt="image" src="https://user-images.githubusercontent.com/80776287/193793537-30511b8f-6ea6-43c5-b38d-6757b73b43f5.png">

**Comment by 7preposition7** [comment]
Please check the tile sheet

**Comment by i9or** [comment]
I guess I’ve checked:

![79A585B0-807B-412C-B760-18537A7C4A04](https://user-images.githubusercontent.com/80776287/193919123-75ec1277-dd28-4cda-a4e8-333e91270096.jpeg)


Or you have updated one at Dropbox?

**Comment by i9or** [comment]
Will be fixed in #8
